name: luna-backend
dependencies:
  - python=3.12.2
  - psycopg2=2.9.9
  - pip=23.3.1
  - pip:
      - django==5.0.3
      - djangorestframework==3.15.0
      - djangorestframework-simplejwt==5.3.1
      - drf-yasg==1.21.7
      - Markdown==3.6.0
      - Pillow==10.2.0
      - gunicorn==21.2.0
      - flake8==7.0.0
      - django-cors-headers==4.3.1