name: luna2
dependencies:
  - python=3.12.4
  - pip
  - psycopg2
  - pip:
    - django==5.0.6
    - djangorestframework==3.15.2
    - flake8
    - djangorestframework-simplejwt==5.3.1
    - flake8
    - gunicorn
    - django-cors-headers==4.3.1
    - pillow==10.3.0
    - drf-yasg==1.21.7

