# Generated by Django 5.0.6 on 2024-07-11 09:37

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_user_path_banner),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_user_path_profile),
        ),
    ]
