# Generated by Django 5.0.6 on 2024-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
