# Generated by Django 5.0.6 on 2024-07-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('restaurant', '0004_alter_restaurant_phone_alter_restaurant_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.categories'),
        ),
    ]
