# Generated by Django 5.0.6 on 2024-07-11 14:27

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.get_restaurant_picture_path),
        ),
    ]
